var introText = '<p>It is a touch screen task where children just touch one of two different images on the left or right, and then the images disappear and some little video-cartoon plays in the middle of the screen depending on which image was touched.  For now, just find whatever 11 second clips on the internet of that can be replaced with other animation-video files once I get that right videos worked out. But work out the structure of how to display them, etc.</p>';

var unsupported = '<p class="warning">Your browser does not support video. Please upgrade before conducting this experiment!</p>';

var endText = '<h1>CONCLUSION</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mollis, sapien eget dignissim rhoncus, nulla nisl luctus ligula, sed sollicitudin augue massa aliquet sem. Cras semper venenatis nulla, sit amet venenatis magna efficitur vel. Morbi ullamcorper nisl finibus elit tempus, quis mattis mauris rutrum. Donec in facilisis nisi. Morbi tincidunt est sit amet lacinia pretium. Nam egestas magna at urna pretium mattis. Phasellus venenatis sem quis justo vulputate, aliquam interdum augue pulvinar. Vivamus eget cursus nunc, vel molestie arcu. In vitae maximus risus, in tristique velit. Quisque erat augue, rutrum in lectus eget, accumsan pellentesque nisl. Nam scelerisque est purus, at vestibulum lectus imperdiet et. In mattis orci sit amet faucibus aliquet. Donec malesuada ultrices metus, a varius dui dignissim non.</p>'+
'<p>Pellentesque volutpat tristique varius. Praesent at nulla viverra, lobortis risus eu, pulvinar sem. Sed ut enim a velit molestie efficitur. Suspendisse euismod, sapien id ullamcorper interdum, mi metus faucibus erat, nec scelerisque ante tortor ac neque. Proin rutrum finibus sem eget ultricies. Fusce ut posuere nisi. Nulla et faucibus sapien. Proin placerat quis elit at auctor. Praesent tincidunt eleifend accumsan. Maecenas ut nibh justo. Etiam libero lectus, sodales id posuere in, elementum at nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ullamcorper velit nec felis lobortis eleifend. Suspendisse egestas vulputate enim eget pellentesque. Morbi consectetur arcu at ante pretium tincidunt.</p>'+
'<p>Phasellus ornare, leo vitae porta volutpat, sapien mi rhoncus dui, sit amet maximus augue massa ac augue. Suspendisse ut posuere turpis. Donec congue diam vitae purus consectetur faucibus. Aliquam ultricies urna in mauris pharetra interdum. Vivamus tincidunt blandit est, in vulputate nisi fermentum et. Sed vestibulum commodo justo sagittis fringilla. Etiam tempor, orci et elementum pellentesque, risus magna mollis eros, nec hendrerit mi purus id est. Donec rhoncus, metus quis hendrerit vehicula, ex nisl porta nunc, sit amet rutrum arcu purus laoreet elit. Integer a leo mauris. Integer eget dui aliquet, accumsan tortor ac, eleifend orci. Sed sagittis convallis posuere. Sed eget porttitor leo. Ut nisi leo, feugiat et fringilla a, vestibulum nec urna. Nulla aliquet euismod arcu at mollis. Ut lobortis ultrices orci eget egestas.</p>'+
'<p>Suspendisse potenti. Mauris at metus eu lectus venenatis sagittis. Ut at congue dolor. Donec eget massa dui. Nunc id blandit elit. Nunc varius lacus a dictum condimentum. Donec aliquet finibus enim non pretium. Nunc pretium euismod ex commodo aliquet. Proin at neque a felis vestibulum hendrerit bibendum id mauris. Proin consectetur, velit quis euismod dapibus, urna mi cursus purus, et vulputate mi nibh eu est. Aliquam ultricies lorem nec cursus maximus. Maecenas venenatis, tellus nec fermentum blandit, nibh ex consequat neque, quis placerat nisl magna vitae lacus. Suspendisse id enim non leo pellentesque varius at vitae nunc.</p>'+
'<p>Nullam in lectus eget arcu eleifend venenatis ac in risus. Nam venenatis consequat urna, sit amet gravida massa pretium ut. Vivamus non risus ac risus egestas semper. Aenean nisi tellus, hendrerit sed fermentum eget, elementum vel risus. Donec nulla lorem, rutrum eget massa vitae, mattis varius erat. Proin vehicula lectus sed est mollis, vel vestibulum metus rutrum. Etiam laoreet augue lectus, quis posuere arcu consectetur eu. In hac habitasse platea dictumst. Integer consequat, est eu pellentesque vulputate, justo ante viverra ipsum, vitae euismod est orci ac magna.</p>';
function resultsPage(results)
{
	return '<h1>Experiment results</h1><br> <p>Uploading to Google Drive now</p>' + '<pre>' + JSON.stringify(results,  null, '\t') + '</pre>' ;
}
